//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShiftCaptain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Building
    {
        public Building()
        {
            this.Rooms = new HashSet<Room>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> AddressId { get; set; }
        public string PhoneNumber { get; set; }
        public string ManagerPhone { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual ICollection<Room> Rooms { get; set; }
    }
}
