//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShiftCaptain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomInstance
    {
        public RoomInstance()
        {
            this.RoomHours = new HashSet<RoomHour>();
        }
    
        public int Id { get; set; }
        public int RoomId { get; set; }
        public int VersionId { get; set; }
    
        public virtual Room Room { get; set; }
        public virtual ICollection<RoomHour> RoomHours { get; set; }
        public virtual Version Version { get; set; }
    }
}
