//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShiftCaptain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomView
    {
        public int BuildingId { get; set; }
        public string BuildingName { get; set; }
        public int RoomId { get; set; }
        public string Name { get; set; }
        public string RoomNumber { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<int> RoomInstanceId { get; set; }
        public Nullable<int> VersionId { get; set; }
        public Nullable<int> SundayId { get; set; }
        public Nullable<int> SundayInstanceId { get; set; }
        public Nullable<System.TimeSpan> SundayStartTime { get; set; }
        public Nullable<decimal> SundayDuration { get; set; }
        public Nullable<int> MondayId { get; set; }
        public Nullable<int> MondayInstanceId { get; set; }
        public Nullable<System.TimeSpan> MondayStartTime { get; set; }
        public Nullable<decimal> MondayDuration { get; set; }
        public Nullable<int> TuesdayId { get; set; }
        public Nullable<int> TuesdayInstanceId { get; set; }
        public Nullable<System.TimeSpan> TuesdayStartTime { get; set; }
        public Nullable<decimal> TuesdayDuration { get; set; }
        public Nullable<int> WednesdayId { get; set; }
        public Nullable<int> WednesdayInstanceId { get; set; }
        public Nullable<System.TimeSpan> WednesdayStartTime { get; set; }
        public Nullable<decimal> WednesdayDuration { get; set; }
        public Nullable<int> ThursdayId { get; set; }
        public Nullable<int> ThursdayInstanceId { get; set; }
        public Nullable<System.TimeSpan> ThursdayStartTime { get; set; }
        public Nullable<decimal> ThursdayDuration { get; set; }
        public Nullable<int> FridayId { get; set; }
        public Nullable<int> FridayInstanceId { get; set; }
        public Nullable<System.TimeSpan> FridayStartTime { get; set; }
        public Nullable<decimal> FridayDuration { get; set; }
        public Nullable<int> SaturdayId { get; set; }
        public Nullable<int> SaturdayInstanceId { get; set; }
        public Nullable<System.TimeSpan> SaturdayStartTime { get; set; }
        public Nullable<decimal> SaturdayDuration { get; set; }
    }
}
