//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShiftCaptain.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShiftCaptainEntities : DbContext
    {
        public ShiftCaptainEntities()
            : base("name=ShiftCaptainEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Address> Addresses { get; set; }
        public DbSet<Building> Buildings { get; set; }
        public DbSet<Preference> Preferences { get; set; }
        public DbSet<Room> Rooms { get; set; }
        public DbSet<RoomHour> RoomHours { get; set; }
        public DbSet<RoomInstance> RoomInstances { get; set; }
        public DbSet<Shift> Shifts { get; set; }
        public DbSet<ShiftPreference> ShiftPreferences { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<UserInstance> UserInstances { get; set; }
        public DbSet<Version> Versions { get; set; }
        public DbSet<BuildingView> BuildingViews { get; set; }
        public DbSet<RoomView> RoomViews { get; set; }
        public DbSet<UserView> UserViews { get; set; }
    }
}
