//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShiftCaptain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShiftPreference
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int VersionId { get; set; }
        public int PreferenceId { get; set; }
        public int Day { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan Duration { get; set; }
    
        public virtual Preference Preference { get; set; }
        public virtual User User { get; set; }
        public virtual Version Version { get; set; }
    }
}
