//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShiftCaptain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Shifts = new HashSet<Shift>();
            this.ShiftPreferences = new HashSet<ShiftPreference>();
            this.UserInstances = new HashSet<UserInstance>();
        }
    
        public int Id { get; set; }
        public string EmailAddress { get; set; }
        public string Pass { get; set; }
        public string FName { get; set; }
        public string MName { get; set; }
        public string LName { get; set; }
        public string NickName { get; set; }
        public Nullable<int> AddressId { get; set; }
        public string EmployeeId { get; set; }
        public string PhoneNumber { get; set; }
        public bool IsShiftManager { get; set; }
        public bool IsManager { get; set; }
        public bool Locked { get; set; }
        public int NumTries { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public bool IsActive { get; set; }
        public bool IsMale { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual ICollection<Shift> Shifts { get; set; }
        public virtual ICollection<ShiftPreference> ShiftPreferences { get; set; }
        public virtual ICollection<UserInstance> UserInstances { get; set; }
    }
}
