//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShiftCaptain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserView
    {
        public int UserId { get; set; }
        public string EmailAddress { get; set; }
        public string Pass { get; set; }
        public string FName { get; set; }
        public string MName { get; set; }
        public string LName { get; set; }
        public string NickName { get; set; }
        public string EmployeeId { get; set; }
        public string PhoneNumber { get; set; }
        public bool IsShiftManager { get; set; }
        public bool IsManager { get; set; }
        public bool Locked { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public bool IsActive { get; set; }
        public bool IsMale { get; set; }
        public Nullable<System.TimeSpan> MinHours { get; set; }
        public Nullable<System.TimeSpan> MaxHours { get; set; }
        public Nullable<decimal> CurrentHours { get; set; }
        public Nullable<int> VersionId { get; set; }
        public Nullable<int> AddressId { get; set; }
        public string Line1 { get; set; }
        public string Line2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string Country { get; set; }
    }
}
