//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShiftCaptain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Version
    {
        public Version()
        {
            this.RoomInstances = new HashSet<RoomInstance>();
            this.Shifts = new HashSet<Shift>();
            this.ShiftPreferences = new HashSet<ShiftPreference>();
            this.UserInstances = new HashSet<UserInstance>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public bool IsActive { get; set; }
        public bool IsVisible { get; set; }
        public bool IsReadyForApproval { get; set; }
        public bool IsApproved { get; set; }
    
        public virtual ICollection<RoomInstance> RoomInstances { get; set; }
        public virtual ICollection<Shift> Shifts { get; set; }
        public virtual ICollection<ShiftPreference> ShiftPreferences { get; set; }
        public virtual ICollection<UserInstance> UserInstances { get; set; }
    }
}
